---
# control

control:
  data_name: CIFAR10
  model_name: resnet9
  active_rate: '0.1'
  num_clients: '5'
  # fraction of active clients per iteration
  # active_rate: '0.1'
  # non-iid args form: non-iid-l-2
  data_split_mode: 'iid'
  algo_mode: 'dynamicsgd'
  # maximum local gradient update
  max_local_gradient_update: '10'
  # how to select client in dynamicFL
  select_client_mode: 'fix'
  # client ratio of assigning number of uploads
  client_ratio: '0.2-0.3-0.5'
  # number of uploads
  number_of_uploads: '2-3-4'
  
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
world_size: 1
resume_mode: 0
verbose: False